#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

~/.config/polybar/./launch.sh

bspc config border_width        0
bspc config window_gap          5

bspc config top_padding         44
bspc config bottom_padding      4
bspc config left_padding        4
bspc config right_padding       4

bspc config borderless_monocle   true
bspc config focus_follows_pointer true

feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.png

#picom &

xsetroot -cursor_name left_ptr &
