#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        1
bspc config window_gap          4

bspc config top_padding         30
bspc config bottom_padding      1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

~/.config/polybar/./launch.sh

feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.png

picom --experimental-backends &

xsetroot -cursor_name left_ptr &

