user: 230
group: 187
permission:
  read: 34
  write: 26
  exec: 88
  exec-sticky: 90
  no-access: 245
  octal: 181
  acl: 130
  context: 168
date:
  hour-old: 40
  day-old: 42
  older: 36
size:
  none: 245
  small: 229
  medium: 216
  large: 172
inode:
  valid: 163
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
git-status:
  default: 245
  unmodified: 245
  ignored: 245
  new-in-index: 28
  new-in-workdir: 28
  typechange: 212
  deleted: 88
  renamed: 25
  modified: 178
  conflicted: 54